2025-04-14 16:42:53,399 INFO    MainThread:1634400 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/ccl/safer/Fedopstest/wandb/run-20250414_164253-oc6yxanw/logs/debug.log
2025-04-14 16:42:53,399 INFO    MainThread:1634400 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/ccl/safer/Fedopstest/wandb/run-20250414_164253-oc6yxanw/logs/debug-internal.log
2025-04-14 16:42:53,400 INFO    MainThread:1634400 [wandb_init.py:init():781] calling init triggers
2025-04-14 16:42:53,400 INFO    MainThread:1634400 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'learning_rate': 0, 'optimizer': '', 'dataset': '', 'model_architecture': '', 'batch_size': 0, 'epochs': 0, 'num_rounds': 0, '_wandb': {}}
2025-04-14 16:42:53,400 INFO    MainThread:1634400 [wandb_init.py:init():809] starting backend
2025-04-14 16:42:53,400 INFO    MainThread:1634400 [wandb_init.py:init():813] sending inform_init request
2025-04-14 16:42:53,402 INFO    MainThread:1634400 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-14 16:42:53,403 INFO    MainThread:1634400 [wandb_init.py:init():823] backend started and connected
2025-04-14 16:42:53,410 INFO    MainThread:1634400 [wandb_init.py:init():915] updated telemetry
2025-04-14 16:42:53,417 INFO    MainThread:1634400 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-14 16:42:54,130 INFO    MainThread:1634400 [wandb_init.py:init():1014] starting run threads in backend
2025-04-14 16:42:54,244 INFO    MainThread:1634400 [wandb_run.py:_console_start():2454] atexit reg
2025-04-14 16:42:54,244 INFO    MainThread:1634400 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-14 16:42:54,244 INFO    MainThread:1634400 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-14 16:42:54,244 INFO    MainThread:1634400 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-14 16:42:54,245 INFO    MainThread:1634400 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-14 16:43:35,411 INFO    MainThread:1634400 [wandb_run.py:_config_callback():1327] config_cb None None {'dataset': 'MNIST', 'model_architecture': 'MNISTClassifier'}
2025-04-14 16:43:35,411 INFO    MainThread:1634400 [wandb_run.py:_finish():2189] finishing run rirakang123/MNIST_test1/oc6yxanw
2025-04-14 16:43:35,412 INFO    MainThread:1634400 [wandb_run.py:_atexit_cleanup():2419] got exitcode: 0
2025-04-14 16:43:35,412 INFO    MainThread:1634400 [wandb_run.py:_restore():2401] restore
2025-04-14 16:43:35,412 INFO    MainThread:1634400 [wandb_run.py:_restore():2407] restore done
2025-04-14 16:43:36,755 INFO    MainThread:1634400 [wandb_run.py:_footer_history_summary_info():4064] rendering history
2025-04-14 16:43:36,755 INFO    MainThread:1634400 [wandb_run.py:_footer_history_summary_info():4096] rendering summary
2025-04-14 16:43:36,756 INFO    MainThread:1634400 [wandb_run.py:_footer_sync_info():4025] logging synced files
